# Generated by Django 4.1.4 on 2023-03-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EVENT_BY_COMPANY_NAME', models.CharField(max_length=200)),
                ('CITY_NAME', models.CharField(max_length=200)),
                ('HOTEL_NAME', models.CharField(max_length=200)),
                ('TOTAL_GIRLS_WITH_WORK_AND_DRESS_CODE', models.CharField(default=0, max_length=200)),
                ('TOTAL_BOYS_WITH_WORK_AND_DRESS_CODE', models.CharField(default=0, max_length=200)),
                ('DATE_FROM', models.DateField()),
                ('DATE_TO', models.DateField()),
                ('FOOD_INCLUDE', models.BooleanField(default=False)),
                ('PAYMENT_PER_PERSON', models.CharField(max_length=200)),
                ('PAYMENT_MODE', models.CharField(choices=[('ONLINE', 'ONLINE'), ('CASH', 'CASH'), ('CHEQUE', 'CHEQUE')], max_length=200)),
                ('PAYMENT_STATUS', models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('HALFPAID', 'HALFPAID')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Eventvideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIDEOS', models.FileField(upload_to='VIDEOS/')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evevnt.event')),
            ],
        ),
        migrations.CreateModel(
            name='EVENTphotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PHOTOS', models.FileField(upload_to='PHOTOS/')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evevnt.event')),
            ],
        ),
    ]
